# Generated by Django 5.0 on 2023-12-14 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('Used', 'Used'), ('New', 'New')], default='Used', max_length=40)),
                ('product_type', models.CharField(choices=[('Bike', 'Bike'), ('Parts', 'Parts'), ('Other', 'Other')], default='Other', max_length=40)),
                ('sale_type', models.CharField(choices=[('Available for pick up', 'Pick Up'), ('Available for shipping', 'Ship')], default='Available for shipping', max_length=40)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('main_photo', models.ImageField(blank=True, upload_to='photos')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos')),
                ('list_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Listings',
            },
        ),
    ]
