# Generated by Django 5.0 on 2023-12-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listings_contact_email_listings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
