# Generated by Django 5.0 on 2023-12-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listings_contact_email_alter_listings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='user',
        ),
    ]
